# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:38:02+00:00



import argparse
import json
import os
from typing import *

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity
from fastapi import UploadFile

from models import SvgconvertPostResponse

app = MCPProxy(
    contact={
        'email': 'kevin@presalytics.io',
        'name': 'Presalytics.io',
        'url': 'http://presalytics.io',
    },
    description='This api converts file formats of OpenXml and OpenOffice documents formats to vector files (e.g., svg)',
    license={'name': 'AGPL'},
    title='Doc Converter',
    version='0.1',
    servers=[
        {
            'description': 'Base server',
            'url': 'https://api.presalytics.io/doc-converter/',
        }
    ],
)


@app.post('/svgconvert', tags=['file_format_conversion'])
def svgconvert(file: UploadFile):
    """
    converts pptx file to svg image
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
