# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:38:02+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class SvgconvertPostRequest(BaseModel):
    file: Optional[bytes] = None


class SvgconvertPostResponse(BaseModel):
    blob_name: Optional[str] = None
    blob_url: Optional[str] = None
